
only_if: $CIRRUS_BRANCH == 'master'

macM1_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-base:latest
  script: |
    brew update
    brew upgrade
    brew install iltommi/brews/hdf5-parallel python3
    OMPI_CXX=g++-12 PYTHONEXE=python3 HDF5_ROOT_DIR="$(brew --prefix hdf5-parallel)" make -j4
    ./smilei benchmarks/tst2d_00_em_propagation.py
     
