name: macos_compile

on:
  push:
    branches: [ master, develop, CI ]
  pull_request:
    branches: [ master, develop, CI ]

jobs:

  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: update
        run: sudo apt-get --allow-releaseinfo-change update -y 
      - name: python
        run: |
          brew install iltommi/brews/smilei --HEAD --only-dependencies
      - name: compile Smilei
        run: |
          export OMPI_CXX=g++-14
          make
